apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-storage
spec:
  serviceName: svc-store
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - name: storage
          image: ghcr.io/tuusuario/api-gw:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: svc-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: svc-storage
      spec:
        accessModes: "ReadWriteOnce"
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
